/* Author       : Don MacSween
 * email        : dm1200@student.aru.ac.uk
 * License      : CC BY 4.0 https://creativecommons.org/licenses/by/4.0/
 * Last Modified: 11/10/2024
 * Purpose : This script is the base class for all settlers in the game.
 *           It contains all the basic information about a settler that is needed to manage their needs and actions.
 */


using System.Collections.Generic;
using UnityEngine;

namespace Settler
{
    public class Settler : MonoBehaviour
    {
        [Tooltip("Uses the Gender emum from SettlerEnumerators.cs- Gender.Male / Gender.Female")]
        public Gender gender;     // there is no historical evidence of other gender descriptors from the Settler era
        
        [Tooltip("randomly generated by the settlerFactory by gender")]
        public string foreName;

        // randomly generated by the settlerFactory for arriving settlers - inherited from parents for born settlers
        [Header("Fore Name"), Tooltip("randomly generated by the settlerFactory by gender")]
        public string      surName;

        // a unique ID for the family the settler belongs to
        public int         familyID;

        // current age of the settler;
        public int age;

        // the world day that the settler was born on - pending world time system.
        public int worldDayBorn;

        // composes a list of skills that the settler has, these can be used to determine settler status and modify the settler's tasks
        [Header("Stats"), Tooltip("a struct of stats that the settler has")]
        public SettlerStats stats;

        // composes a list of skills that the settler has, these can be used to determine settler status and modify the settler's tasks
        [Header("SKills"), Tooltip("a struct of stats that the settler has")]
        private List<SettlerSkills>  skills;

        void Start() 
        {
        
        }

        
    }
}
